@startuml

title __MIWOK's Class Diagram__\n

  package com.example.android.miwok {
    class ColorsActivity {
        - mMediaPlayer : MediaPlayer
        - mAudioManager : AudioManager
        - mCompletionListener : OnCompletionListener
        - mOnAudioFocusChangeListener : OnAudioFocusChangeListener
        # onCreate()
        # onStop()
        - releaseMediaPlayer()
    }
  }
  

  package android.support.v4 {
    class HostCallbacks {
        + HostCallbacks()
        + onDump()
        + onShouldSaveFragmentState()
        + onGetLayoutInflater()
        + onGetHost()
        + onSupportInvalidateOptionsMenu()
        + onStartActivityFromFragment()
        + onStartActivityFromFragment()
        + onStartIntentSenderFromFragment()
        + onRequestPermissionsFromFragment()
        + onShouldShowRequestPermissionRationale()
        + onHasWindowAnimations()
        + onGetWindowAnimations()
        + onAttachFragment()
        + onFindViewById()
        + onHasView()
    }
  }
  

  package android.support.v4 {
    class NonConfigurationInstances {
        ~ custom : Object
        ~ viewModelStore : ViewModelStore
        ~ fragments : FragmentManagerNonConfig
        ~ NonConfigurationInstances()
    }
  }
  

  package android.support.v4 {
    class ExtraData {
        + ExtraData()
    }
  }
  

  package com.example.android.miwok {
    class FamilyActivity {
        - mMediaPlayer : MediaPlayer
        - mAudioManager : AudioManager
        - mCompletionListener : OnCompletionListener
        - mOnAudioFocusChangeListener : OnAudioFocusChangeListener
        # onCreate()
        # onStop()
        - releaseMediaPlayer()
    }
  }
  

  package android.support.v4 {
    class HostCallbacks {
        + HostCallbacks()
        + onDump()
        + onShouldSaveFragmentState()
        + onGetLayoutInflater()
        + onGetHost()
        + onSupportInvalidateOptionsMenu()
        + onStartActivityFromFragment()
        + onStartActivityFromFragment()
        + onStartIntentSenderFromFragment()
        + onRequestPermissionsFromFragment()
        + onShouldShowRequestPermissionRationale()
        + onHasWindowAnimations()
        + onGetWindowAnimations()
        + onAttachFragment()
        + onFindViewById()
        + onHasView()
    }
  }
  

  package android.support.v4 {
    class NonConfigurationInstances {
        ~ custom : Object
        ~ viewModelStore : ViewModelStore
        ~ fragments : FragmentManagerNonConfig
        ~ NonConfigurationInstances()
    }
  }
  

  package android.support.v4 {
    class ExtraData {
        + ExtraData()
    }
  }
  

  package com.example.android.miwok {
    class MainActivity {
        # onCreate()
    }
  }
  

  package android.support.v4 {
    class HostCallbacks {
        + HostCallbacks()
        + onDump()
        + onShouldSaveFragmentState()
        + onGetLayoutInflater()
        + onGetHost()
        + onSupportInvalidateOptionsMenu()
        + onStartActivityFromFragment()
        + onStartActivityFromFragment()
        + onStartIntentSenderFromFragment()
        + onRequestPermissionsFromFragment()
        + onShouldShowRequestPermissionRationale()
        + onHasWindowAnimations()
        + onGetWindowAnimations()
        + onAttachFragment()
        + onFindViewById()
        + onHasView()
    }
  }
  

  package android.support.v4 {
    class NonConfigurationInstances {
        ~ custom : Object
        ~ viewModelStore : ViewModelStore
        ~ fragments : FragmentManagerNonConfig
        ~ NonConfigurationInstances()
    }
  }
  

  package android.support.v4 {
    class ExtraData {
        + ExtraData()
    }
  }
  

  package com.example.android.miwok {
    class NumbersActivity {
        - mMediaPlayer : MediaPlayer
        - mAudioManager : AudioManager
        - mOnAudioFocusChangeListener : OnAudioFocusChangeListener
        - mCompletionListener : OnCompletionListener
        # onCreate()
        # onStop()
        - releaseMediaPlayer()
    }
  }
  

  package android.support.v4 {
    class HostCallbacks {
        + HostCallbacks()
        + onDump()
        + onShouldSaveFragmentState()
        + onGetLayoutInflater()
        + onGetHost()
        + onSupportInvalidateOptionsMenu()
        + onStartActivityFromFragment()
        + onStartActivityFromFragment()
        + onStartIntentSenderFromFragment()
        + onRequestPermissionsFromFragment()
        + onShouldShowRequestPermissionRationale()
        + onHasWindowAnimations()
        + onGetWindowAnimations()
        + onAttachFragment()
        + onFindViewById()
        + onHasView()
    }
  }
  

  package android.support.v4 {
    class NonConfigurationInstances {
        ~ custom : Object
        ~ viewModelStore : ViewModelStore
        ~ fragments : FragmentManagerNonConfig
        ~ NonConfigurationInstances()
    }
  }
  

  package android.support.v4 {
    class ExtraData {
        + ExtraData()
    }
  }
  

  package com.example.android.miwok {
    class PhrasesActivity {
        - mMediaPlayer : MediaPlayer
        - mAudioManager : AudioManager
        - mCompletionListener : OnCompletionListener
        - mOnAudioFocusChangeListener : OnAudioFocusChangeListener
        # onCreate()
        # onStop()
        - releaseMediaPlayer()
    }
  }
  

  package android.support.v4 {
    class HostCallbacks {
        + HostCallbacks()
        + onDump()
        + onShouldSaveFragmentState()
        + onGetLayoutInflater()
        + onGetHost()
        + onSupportInvalidateOptionsMenu()
        + onStartActivityFromFragment()
        + onStartActivityFromFragment()
        + onStartIntentSenderFromFragment()
        + onRequestPermissionsFromFragment()
        + onShouldShowRequestPermissionRationale()
        + onHasWindowAnimations()
        + onGetWindowAnimations()
        + onAttachFragment()
        + onFindViewById()
        + onHasView()
    }
  }
  

  package android.support.v4 {
    class NonConfigurationInstances {
        ~ custom : Object
        ~ viewModelStore : ViewModelStore
        ~ fragments : FragmentManagerNonConfig
        ~ NonConfigurationInstances()
    }
  }
  

  package android.support.v4 {
    class ExtraData {
        + ExtraData()
    }
  }
  

  package com.example.android.miwok {
    class Word {
        - mDefaultTranslation : String
        - mMiwokTranslation : String
        - mAudioResourceId : int
        - mImageResourceId : int
        {static} - NO_IMAGE_PROVIDED : int
        + Word()
        + Word()
        + getDefaultTranslation()
        + getMiwokTranslation()
        + getImageResourceId()
        + hasImage()
        + getAudioResourceId()
    }
  }
  

  package com.example.android.miwok {
    class WordAdapter {
        - mColorResourceId : int
        + WordAdapter()
        + getView()
    }
  }
  

  ColorsActivity -up-|> AppCompatActivity
  ColorsActivity +-down- HostCallbacks
  ColorsActivity +-down- NonConfigurationInstances
  ColorsActivity +-down- ExtraData
  HostCallbacks -up-|> FragmentHostCallback
  FamilyActivity -up-|> AppCompatActivity
  FamilyActivity +-down- HostCallbacks
  FamilyActivity +-down- NonConfigurationInstances
  FamilyActivity +-down- ExtraData
  HostCallbacks -up-|> FragmentHostCallback
  MainActivity -up-|> AppCompatActivity
  MainActivity +-down- HostCallbacks
  MainActivity +-down- NonConfigurationInstances
  MainActivity +-down- ExtraData
  HostCallbacks -up-|> FragmentHostCallback
  NumbersActivity -up-|> AppCompatActivity
  NumbersActivity +-down- HostCallbacks
  NumbersActivity +-down- NonConfigurationInstances
  NumbersActivity +-down- ExtraData
  HostCallbacks -up-|> FragmentHostCallback
  PhrasesActivity -up-|> AppCompatActivity
  PhrasesActivity +-down- HostCallbacks
  PhrasesActivity +-down- NonConfigurationInstances
  PhrasesActivity +-down- ExtraData
  HostCallbacks -up-|> FragmentHostCallback
  WordAdapter -up-|> ArrayAdapter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
